### ISSUE TITLE
[Feature] help moderators to better understand "pass" rates on comments

### ISSUE THREAD

**Issue by patcon** [pol-is/issues#37]
With [mydem0cracy.ca](mydem0cracy.ca), we encourage participants to click "Pass / Unsure" if they find a question overly confusing, or disagree with a premise. One participant wondered what effect this would have, and [asked if it pushed those comments to the bottom](https://www.reddit.com/r/CanadaPolitics/comments/5jkwuw/mydem0cracyca_an_open_citizenled_consultation_on/dbhk1nu/)

I admitted that we had no way to act on it, but the plan was to review those comments and remove them if we judged them to be convoluted.

But there's no way to act on that from our end, aside from downloading the raw data and analyzing it every so often.

Might there be a moderator feature you could add to address this? Thanks!

**Comment by mbjorkegren** [comment]
We actually just deployed something that well help with that :)
You can now see the percent of agrees, disagrees, and passes in the comment moderation view.

**Comment by patcon** [comment]
Amazing! Thanks!

**Comment by patcon** [comment]
FYI, until there's some sort of sort feature (should i create a new placeholder issue for that?), other's can CTRL+F search for this string (with newline), you can quickly skim large numbers of 30% and 40% pass rate comments:

    passed
    4

pasting it into search results in this:

![screenshot of search bar](https://imgur.com/P9YMBgT.png)

So you get this search:

![screenshot of highlighted search text](https://imgur.com/EGyo1VZ.png)

**Comment by mbjorkegren** [comment]
cool! how did you insert the newline character?

**Comment by patcon** [comment]
Just copying from my codeblock quote above works. Any copied newline shows as that wonky "N/L" character when pasted into the search bar ;)
