### ISSUE TITLE
[support]: insight on api error

### ISSUE THREAD

**Issue by patcon** [pol-is/issues#40]
I'm trying to put together an API proxy to help demo the direction I hope the API design will go in. I've done this before in a few other situations, using the same tool I'm using [here](https://github.com/patcon/polis-api-proxy), and didn't expect it to be very difficult.

Having said that, I'm running into some odd errors that are throwing me for a loop:

```
/non_encrypted/repos/polis-api-proxy (master ✘)✹✭ ᐅ http 'http://localhost:5000/api/v3/conversations/5mnfxu85hx' Authorization:pkey_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   
HTTP/1.1 403 Forbidden
CF-RAY: 319bff96bcb527c2-YYZ
Cache-Control: no-cache
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 240
Content-Type: text/html; charset=utf-8
Date: Sat, 31 Dec 2016 07:25:35 GMT
Server: cloudflare-nginx
Set-Cookie: __cfduid=d71127c3344a4a0d17972e0708a6a58191483169135; expires=Sun, 31-Dec-17 07:25:35 GMT; path=/; domain=.pol.is; HttpOnly
Transfer-Encoding: chunked
Vary: Accept-Encoding
Via: 1.1 vegur
X-Amz-Id-2: jcy9EdKNQOMKoSelIX4mNyhAmEIDYrwQFQ9W1nYRND2+CrW2umoxJTrUy+NH3TD9p5cP6LKjvHM=
X-Amz-Request-Id: 94ADFDDEBCE10DF3

<html>
<head><title>403 Forbidden</title></head>
<body>
<h1>403 Forbidden</h1>
<ul>
<li>Code: AccessDenied</li>
<li>Message: Access Denied</li>
<li>RequestId: 94ADFDDEBCE10DF3</li>
<li>HostId: jcy9EdKNQOMKoSelIX4mNyhAmEIDYrwQFQ9W1nYRND2+CrW2umoxJTrUy+NH3TD9p5cP6LKjvHM=</li>
</ul>
<hr/>
</body>
</html>
```

Do you have any insight on what might be causing this? It works fine with some of the features I've added, but not for others. For example:
- using the proxy to send the api key in a header instead of basic auth username works
- using the proxy to rewrite the conversation_id from the path into the param that you accept, this doesn't seem to work for some reason (even though it seems to be hitting the correct url)

Any insight into the error on your end would be greatly appreciated! Thanks! :)

**Comment by mbjorkegren** [comment]
That route isn't matching any of our routes, so it hits our default route handler which looks for files on S3.

**Comment by patcon** [comment]
Thanks Mike :) Obviously, it ended up being an oversight on my end. But your confirming so gave me resolve to dive in with fresh eyes :)
