### ISSUE TITLE
Preserve slack history for future generations

### ISSUE THREAD

**Issue by patcon** [pol-is/issues#44]
### Relevant info

* free slack tier hides messages older than 10,000 ago
* paid and non-profit tier do away with this restriction
* 10,000 msg exports are possible on free tier
* full exports will require costs down the road
* slack history is important, as lots of tech questions are asked/answered and organizational history and progress is searchable
* rocketchat, a self-hosted open source slack alternative, [allows dedup'd imports of slack backup files](https://github.com/RocketChat/Rocket.Chat/pull/3123), ie. can import a bunch of previous slack backups

### Recommendation

I'd recommend Team Polis setting calendar reminders and start taking semi-regular backups (once every few months, depending on msg load) so that history is preserved.

For a small amount of inconvenience, this will allow for the maximum possible future opportunity space to be available. You can decide to pay for Slack premium, or you could decide to migrate to another platform without penalty of losing history.

**Comment by colinmegill** [comment]
Metapolis related issue, resolved off thread - thanks Pat!
