### ISSUE TITLE
Fix /about routing

### ISSUE THREAD

**Issue by metasoarous** [pol-is/issues#47]
When I type https://pol.is/about into a browser, it redirects to https://pol.is/gov, as expected. However, there's a link out to it here (https://clojure.org/community/companies), and when I click it I get this:

![image](https://cloud.githubusercontent.com/assets/88556/24078333/bf4c654e-0ca5-11e7-8c0f-34f55bbb60c3.png)

This is rather bizzare; I've never seen anything quite like this. It would seem that it has something to do with the authorization, but I can't fathom why that would be different in the two situations. I can verify that I get the same behavior when using a private window (FWIW) so it doesn't have to do with being logged in.

I think it's a good idea to keep this route working, as it used to be our defacto lander, and there are bound to be plenty of references to it out there.

**Comment by mbjorkegren** [comment]
oh funny, it's the slash. We'll just need to redirect anything ending in slash.
It's nothing to do with our auth, the 403 message is returned by S3. We proxy to S3 for any paths that aren't handled by the server. S3 is saying "this user doesn't have enough permission to know if there is a file called "about" in this bucket.

**Comment by metasoarous** [comment]
Hahaha! Good find.
