### ISSUE TITLE
topic and description data attributes

### ISSUE THREAD

**Issue by virgile-dev** [pol-is/issues#79]
Hey guys, 

We been testing the "integrate on your entire site" feature of pol.is which generates conversation automatically for every new page_id with : 

```
<div
  class="polis"
  data-page_id="PAGE_ID"
  data-site_id="polis_site_id">
</div>
<script async="true" src="https://pol.is/embed.js"></script>
``` 
So this works great you can even do lots of configuration with data templating using `data-ucv`, `data-ucw` and `data-show_vis`. 

The problem is when you start having lots of pages you conversation list starts looking like this:
<img width="700" alt="capture d ecran 2017-11-08 a 12 38 45" src="https://user-images.githubusercontent.com/11473995/32547236-dcb07cc6-c481-11e7-90c3-cfecdbaab203.png">

Which makes it really hard to find and access the conversation you are looking for.

As I've talking to Colin, for simplicity it's best to go full iframe when doing an integration rather than using the Pol.is API.

So in that line of thinking is there any way or what do you think of passing a ``topic`` and a ``description`` as data attribute to the iframe when it generates the conversation for the 1st time ? 

Pol.is could pick it up assign it to the conversation that was created and display it in the list of convos and even on the iframe. 

What do you think ?

**Comment by mbjorkegren** [comment]
(editing my reply after looking at the code) It looks like "data-topic" should be there, let me know if it doesn't work for you. I'm not sure if we can support description at the moment (without some rearchitecture), since the value may be too long to encode in a URL.

**Comment by virgile-dev** [comment]
Hey @mbjorkegren , 

Yes this does help a lot thanks !
