### ISSUE TITLE
Help with swagger docs' interactive features

### ISSUE THREAD

**Issue by patcon** [pol-is/issues#8]
So the best part about a swagger spec is that it creates interactive docs in the browser:
http://petstore.swagger.io/?url=https://patcon.github.io/polis-api-spec/swagger.json#!/Conversations/get_conversations

For the interactive docs to work, the endpoint needs to allow CORS support (since the docs page is hosted on a non-pol.is domain.) Usually, I'd get around this by setting up a simple [Argo](https://github.com/argo/argo#adding-cross-origin-resource-sharing) API proxy, like I've done here: https://github.com/patcon/polis-api-proxy

In the pol.is Swagger API docs, I've subbed in the proxy host, and you'll see that if you test it out here:
http://petstore.swagger.io/?url=https://patcon.github.io/polis-api-spec/swagger.json#!/Conversations/get_conversations

But I'm really confused why a 500 error is being thrown. I've confirmed that the proxy works via curl, and that only the web ui going through the proxy causes the error. And I've confirmed that that error is not from the proxy, but from the actual pol.is API.

Any idea what is happening on your end? I'm hitting this URL via the Swagger browser API explorer btw:
https://polis-api-proxy.herokuapp.com/api/v3/conversations?conversation_id=78nfpz

**Comment by patcon** [comment]
Interesting. Clicking that final link (to the proxy) gives the 500 error when it's referred, but then if you refresh, it succeeds...

ok, it seems I can maybe dig a little more with this. Any help appreciated though.

**Comment by mbjorkegren** [comment]
Maybe try having the proxy add "https://api.pol.is" an "Origin" header?
See the "addCorsHeader" function in https://github.com/pol-is/polisServer/blob/master/server.js

**Comment by patcon** [comment]
Thanks @mbjorkegren. I'll read up on that. fwiw, I fixed the odd behavior with that link above by having the proxy zero out the "Referer" request header, but the browser ui is still giving a 500. I'll keep at it though -- not out of options yet ;)

**Comment by patcon** [comment]
Yay! The "Origin" suggestion did the trick! Thanks @mbjorkegren!

Swagger docs are now interactive
