### ISSUE TITLE
data-ui_lang not work automatically created conversation (with pol.is-site-id and page-id)

### ISSUE THREAD

**Issue by virgile-dev** [pol-is/issues#88]
## This is a bug

Hey guys ! 

I have a little problem when using the data-attribute `data-ui_lang` (which allows to set the pol.is UI language). 

It works when I embed a conversation I created manually in Pol.is. Ex :
 
```
<div class='polis' data-conversation_id='8eyheurnmd' data-ui_lang="es"></div>
<script async src='https://pol.is/embed.js'></script>
```

**But** it doesn't work when the conversation is created automatically with a pol.is page-id and and a pol.is-site-id. Ex: 
```
<div class='polis column' data-page_id="#" data-site_id="polis_site_id" data-ui_lang="es" > </div>
<script async='true' src='https://pol.is/embed.js' > </script>
```

In this case the UI takes the navigator's language. 

Thanks a lot for your help

**Comment by mbjorkegren** [comment]
Ok should be working now :)

**Comment by will94290** [comment]
Thank you !
